apiVersion: v1
kind: Secret
metadata:
  name: secrets-demo-db
  namespace: default
type: Opaque
data:
  # These values are base64 encoded
  DB_CONNECTION_STRING: U2VydmVyPW15c2VydmVyLmRhdGFiYXNlLndpbmRvd3MubmV0O0RhdGFiYXNlPW15ZGI7VXNlcj1hZG1pbjsK
